### ISSUE TITLE
HTML in the ReadMe

### ISSUE THREAD

**Issue by aloisdg** [d-edge/extLauncher#19]
Hello,

We have HTML in [NuGet](https://www.nuget.org/packages/extLauncher/):

![image](https://user-images.githubusercontent.com/3449303/161943845-3a4922b9-02d2-44d0-955c-46bc9a9c1130.png)

We are using strip html:

https://github.com/d-edge/extLauncher/blob/2b99889ae2667d18a14e6f8f54712f356606f716/.github/workflows/build.yml#L41

There is something to check here :)

**Comment by Tarmil** [comment]
I think it's because the project points to the input readme rather than the output: https://github.com/d-edge/extLauncher/blob/2b99889ae2667d18a14e6f8f54712f356606f716/extLauncher/extLauncher.fsproj#L43

If we change the fsproj, it will point to a file that only exists in the GH action. So I think the best is to use `strip-markdown-html` withou `output-path` so that it modifies the root README in-place.
